version: '3.8'
services:
  db:
    image: postgres:latest
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    expose:
      - "5423"
    command: -p 5423
  api:
    build: .
    command: sh -c "alembic upgrade head && python3 -m uvicorn --host 0.0.0.0 main:app"
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    restart: always
    depends_on:
      - db

volumes:
  pgdata: